### ISSUE TITLE
5.8 129 页

### ISSUE THREAD

**Issue by zhouchongzxc** [Dream4ever/Chinese-Errata-for-JavaScript-The-Definitive-Guide#5]
var name=[=expr]

应该是 var name [= expr]

**Comment by Dream4ever** [comment]
多谢，已更正。不过应该是 `var name=[expr][,...];` 吧？

**Comment by zhouchongzxc** [comment]
= 不是必须的 
var x = ; 会出错
[ ] 在语法表示中的意思是可选

**Comment by Dream4ever** [comment]
还真是如此，自己之前看的不仔细，受教了。
